In [19]:
import os
import imagehash
from PIL import Image
from tqdm import tqdm
from pathlib import Path
import pandas as pd

In [12]:
def find_duplicates(image_dir):
    
    hashes = {}
    duplicates = []

    for root, dirs, files in os.walk(image_dir):
        for file in files:
            
            if file.lower().endswith(('.png','.jpg','.jpeg','.bmp','.tiff')):
                
                path = os.path.join(root, file)

                try:
                    img = Image.open(path)
                    img_hash = imagehash.phash(img)

                    if img_hash in hashes:
                        duplicates.append((path, hashes[img_hash]))
                    else:
                        hashes[img_hash] = path

                except Exception as e:
                    print("Error reading:", path)

    return duplicates

In [3]:
os.getcwd()

'/Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/notebooks'

In [4]:
os.chdir("..")
os.getcwd()

'/Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification'

In [7]:
BASE_DIR = Path.cwd()

In [8]:
BASE_DIR

PosixPath('/Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification')

In [9]:
DIR_1 = BASE_DIR / "data" / "consolidated" / "Stage-2" / "Battery"

In [10]:
DIR_1

PosixPath('/Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery')

In [15]:
DIR_2 = BASE_DIR / "data" / "consolidated" / "Stage-1" / "Non_Organic"

In [13]:
duplicates = find_duplicates(DIR_1)

print("Number of duplicates:", len(duplicates))

Number of duplicates: 4

In [14]:
for dup in duplicates[:10]:
    print("Duplicate:", dup[0])
    print("Original :", dup[1])
    print()

Duplicate: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_cd98ec8a.jpg
Original : /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_a859ac79.jpg

Duplicate: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_74f971b5.jpg
Original : /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_ee900c37.jpg

Duplicate: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_b2e96ed3.jpg
Original : /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_2d20e82f.jpg

Duplicate: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_3ab28792.jpg
Original : /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Battery/garbage_classification_Non_Organic_Battery_cdb5e985.jpg

In [16]:
duplicates_no = find_duplicates(DIR_2)

print("Number of duplicates:", len(duplicates_no))

/opt/anaconda3/envs/t3_project_clone/lib/python3.11/site-packages/PIL/Image.py:970: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

Number of duplicates: 2680

In [20]:
non_o_duplicates_df = pd.DataFrame(duplicates_no, columns=['duplicate', 'original'])

In [21]:
non_o_duplicates_df

,duplicate,original
0,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
3,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
4,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
...,...,...
2675,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2676,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2677,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2678,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2679,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...

In [22]:
DIR_3 = BASE_DIR / "data" / "consolidated" / "Stage-1" / "Organic"

In [23]:
duplicates_org = find_duplicates(DIR_3)

print("Number of duplicates:", len(duplicates_org))

Number of duplicates: 1613

In [24]:
org_duplicates_df = pd.DataFrame(duplicates_org, columns=['duplicate', 'original'])

In [25]:
org_duplicates_df

,duplicate,original
0,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
3,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
4,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
...,...,...
1608,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1609,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1610,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1611,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1612,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...

In [26]:
non_o_duplicates_df.to_csv("Non_org_duplicates.csv", index=False)

In [27]:
org_duplicates_df.to_csv("org_duplicates.csv", index=False)

In [28]:
stage2_root = BASE_DIR / "data" / "consolidated" / "Stage-2"

all_duplicates = []
summary = []

for class_folder in os.listdir(stage2_root):

    class_path = os.path.join(stage2_root, class_folder)

    if os.path.isdir(class_path):

        print(f"Checking {class_folder}...")

        duplicates = find_duplicates(class_path)

        summary.append({
            "class": class_folder,
            "duplicate_count": len(duplicates)
        })

        for dup in duplicates:
            all_duplicates.append((class_folder, dup[0], dup[1]))

Checking Paper...
Checking Misc_Trash...
Checking Textile...
Checking Metal...
Checking E_waste...

/opt/anaconda3/envs/t3_project_clone/lib/python3.11/site-packages/PIL/Image.py:970: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

Checking Medical_waste...
Checking Cardboard...
Checking Green_Glass...
Checking Brown_Glass...
Checking Battery...
Checking Plastic...
Checking Shoes...
Checking White_Glass...

In [29]:
duplicates_df = pd.DataFrame(
    all_duplicates,
    columns=["class","duplicate_image","original_image"]
)

In [30]:
summary_df = pd.DataFrame(summary)

print(summary_df)

            class  duplicate_count
0           Paper              596
1      Misc_Trash                5
2         Textile                2
3           Metal              412
4         E_waste              124
5   Medical_waste               13
6       Cardboard              407
7     Green_Glass              100
8     Brown_Glass               88
9         Battery                4
10        Plastic              522
11          Shoes               10
12    White_Glass              268

In [31]:
duplicates_df

,class,duplicate_image,original_image
0,Paper,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
1,Paper,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2,Paper,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
3,Paper,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
4,Paper,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
...,...,...,...
2546,White_Glass,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2547,White_Glass,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2548,White_Glass,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2549,White_Glass,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...
2550,White_Glass,/Users/kalyanivenkateswaran/Documents/T3_Proje...,/Users/kalyanivenkateswaran/Documents/T3_Proje...

In [35]:
import os
import shutil
backup_stg2_dup = BASE_DIR / "data" / "consolidated" / "Stage-2-duplicates"

for _, row in duplicates_df.iterrows():

    class_name = row["class"]
    duplicate_path = row["duplicate_image"]

    # Create class backup folder
    class_backup = os.path.join(backup_stg2_dup, class_name)
    os.makedirs(class_backup, exist_ok=True)

    # Destination path
    filename = os.path.basename(duplicate_path)
    dest_path = os.path.join(class_backup, filename)

    try:
        shutil.move(duplicate_path, dest_path)
        print(f"Moved: {duplicate_path} -> {dest_path}")

    except Exception as e:
        print(f"Error moving {duplicate_path}: {e}")

Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_572638c8.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_572638c8.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_56e546ee.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_56e546ee.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_8940fbd1.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_8940fbd1.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_9dc56753.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_9dc56753.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_9db4de05.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_9db4de05.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_e02c5b90.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_e02c5b90.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_d1e758d3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_d1e758d3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_2cd826ff.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_2cd826ff.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_6aa14400.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_6aa14400.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_120a6863.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_120a6863.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_bf69e6b5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_bf69e6b5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_cdf61445.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_cdf61445.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_b7ca65dd.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_b7ca65dd.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_f14a68e4.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_f14a68e4.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_1f67941a.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_1f67941a.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_db1dfa9d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_db1dfa9d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_9b6a18c7.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_9b6a18c7.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_84e43cd1.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_84e43cd1.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_3021032e.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_3021032e.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_c6cf0db5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_c6cf0db5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_2c0a559c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_2c0a559c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_54411d13.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_54411d13.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_f7afc923.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_f7afc923.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_0f031813.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_0f031813.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_621f08a6.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_621f08a6.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_c9962932.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_c9962932.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_c823a316.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_c823a316.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_a118a7f5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_a118a7f5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_11c4086c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_11c4086c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_747b0005.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_747b0005.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_5e2503a7.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_5e2503a7.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_d3469eb3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_d3469eb3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_25e5e9e7.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_25e5e9e7.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_8ea89853.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_8ea89853.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_e14a8868.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_e14a8868.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_dcb53ee6.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_dcb53ee6.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_35e48a4c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_35e48a4c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_d902b596.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_d902b596.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_fdb73d48.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_fdb73d48.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_5b56ad76.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_5b56ad76.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_4b4f7823.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_4b4f7823.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_d68fa33e.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_d68fa33e.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_b4dd5700.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_b4dd5700.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_65000fea.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_65000fea.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_eb79e465.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_eb79e465.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_d8c6a612.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_d8c6a612.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_42c13028.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_42c13028.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_4d93efbb.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_4d93efbb.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_d275d086.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_d275d086.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_e20be1bc.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_e20be1bc.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_2d34416c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_2d34416c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_5a4c094b.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_5a4c094b.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_58afc9fe.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_58afc9fe.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_7bff3e48.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_7bff3e48.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_4dbe8f5b.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_4dbe8f5b.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_1dfa3543.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_1dfa3543.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_2a2d341d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_2a2d341d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_88d86e49.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_88d86e49.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_473cb13b.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_473cb13b.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_79a8b523.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_79a8b523.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_e6856395.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_e6856395.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/Trashnet_Non_Organic_Paper_052130ae.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/Trashnet_Non_Organic_Paper_052130ae.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2/Paper/garbage_classification_Non_Organic_Paper_3a7621b9.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-2-duplicates/Paper/garbage_classification_Non_Organic_Paper_3a7621b9.jpg

In [37]:
import os
import shutil
backup_stg2_dup = BASE_DIR / "data" / "consolidated" / "Stage-1-duplicates"

for _, row in org_duplicates_df.iterrows():

    class_name = "Organic"
    duplicate_path = row["duplicate"]

    # Create class backup folder
    class_backup = os.path.join(backup_stg2_dup, class_name)
    os.makedirs(class_backup, exist_ok=True)

    # Destination path
    filename = os.path.basename(duplicate_path)
    dest_path = os.path.join(class_backup, filename)

    try:
        shutil.move(duplicate_path, dest_path)
        print(f"Moved: {duplicate_path} -> {dest_path}")

    except Exception as e:
        print(f"Error moving {duplicate_path}: {e}")

Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_2aee2cff.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_2aee2cff.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_d83c3294.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_d83c3294.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_878bde7c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_878bde7c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_48afb936.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_48afb936.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_ec1f6af5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_ec1f6af5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_49c06857.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_49c06857.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_7c84d242.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_7c84d242.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_81b4df6b.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_81b4df6b.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_b05c123e.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_b05c123e.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_d525ab4d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_d525ab4d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_1b474001.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_1b474001.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_1600cb24.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_1600cb24.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_a33b980a.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_a33b980a.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_5047b0f2.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_5047b0f2.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_05de9d11.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_05de9d11.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_ab34a788.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_ab34a788.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_81c4c99c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_81c4c99c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_258bae7a.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_258bae7a.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_183ec97f.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_183ec97f.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_3b3bb135.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_3b3bb135.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_f608620f.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_f608620f.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_6ec7097f.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_6ec7097f.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_ab9c38a5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_ab9c38a5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_528b6dda.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_528b6dda.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_60eb1300.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_60eb1300.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_8dd5ffca.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_8dd5ffca.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_81df73ff.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_81df73ff.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_cbb03851.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_cbb03851.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_6b22d74d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_6b22d74d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_9421e8d5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_9421e8d5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_e3ebcff3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_e3ebcff3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_36e1b28d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_36e1b28d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_260f76a0.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_260f76a0.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_c67b944f.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_c67b944f.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_7742f7ed.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_7742f7ed.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_9bbfe1a5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_9bbfe1a5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_c16831b4.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_c16831b4.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_1e6f22cd.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_1e6f22cd.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_dfe6f6bd.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_dfe6f6bd.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_d6366cc3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_d6366cc3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_a0ccc5d0.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_a0ccc5d0.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_d1be5aed.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_d1be5aed.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_6ab06928.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_6ab06928.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_e01ec35c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_e01ec35c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_6b5ed203.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_6b5ed203.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_3df36c16.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_3df36c16.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_8d5c4c5d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_8d5c4c5d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_d3dff564.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_d3dff564.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_67ad58f8.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_67ad58f8.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_cdfd5fb4.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_cdfd5fb4.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_63e2f11d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_63e2f11d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_703d8b96.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_703d8b96.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_73a1a135.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_73a1a135.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_4f982359.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_4f982359.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/garbage_classification_Organic_831d8c21.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/garbage_classification_Organic_831d8c21.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_75215e58.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_75215e58.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_f589471a.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_f589471a.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_653d6716.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_653d6716.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_b98672b2.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_b98672b2.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_5930a5cb.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_5930a5cb.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_fd48b9d4.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_fd48b9d4.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_58ff9ace.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_58ff9ace.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_5243c81c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_5243c81c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/Tricascade_Organic_77d12702.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/Tricascade_Organic_77d12702.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Organic/MendleyGCdataset_Organic_83baa511.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Organic/MendleyGCdataset_Organic_83baa511.jpg

In [38]:
import os
import shutil
backup_stg2_dup = BASE_DIR / "data" / "consolidated" / "Stage-1-duplicates"

for _, row in non_o_duplicates_df.iterrows():

    class_name = "Non_Organic"
    duplicate_path = row["duplicate"]

    # Create class backup folder
    class_backup = os.path.join(backup_stg2_dup, class_name)
    os.makedirs(class_backup, exist_ok=True)

    # Destination path
    filename = os.path.basename(duplicate_path)
    dest_path = os.path.join(class_backup, filename)

    try:
        shutil.move(duplicate_path, dest_path)
        print(f"Moved: {duplicate_path} -> {dest_path}")

    except Exception as e:
        print(f"Error moving {duplicate_path}: {e}")

Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Plastic_64a4b7af.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Plastic_64a4b7af.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Tricascade_Non_Organic_E_waste_28436f21.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Tricascade_Non_Organic_E_waste_28436f21.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Cardboard_0e9c5390.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Cardboard_0e9c5390.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_572638c8.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_572638c8.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_56e546ee.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_56e546ee.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_White_Glass_efdcde29.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_White_Glass_efdcde29.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Cardboard_725fb937.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Cardboard_725fb937.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_614a54ef.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_614a54ef.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_8940fbd1.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_8940fbd1.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_9dc56753.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_9dc56753.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Warp-main_Non_Organic_Plastic_4bff47ef.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Warp-main_Non_Organic_Plastic_4bff47ef.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_9db4de05.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_9db4de05.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Cardboard_840518d3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Cardboard_840518d3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_7bbe0d37.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_7bbe0d37.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_ff06f1cb.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_ff06f1cb.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Plastic_30e40e79.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Plastic_30e40e79.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Green_Glass_5b1576ff.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Green_Glass_5b1576ff.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_e02c5b90.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_e02c5b90.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_d1e758d3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_d1e758d3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Metal_65fe5a37.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Metal_65fe5a37.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Warp-main_Non_Organic_Plastic_1cac3a58.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Warp-main_Non_Organic_Plastic_1cac3a58.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_ac0cc6a2.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_ac0cc6a2.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_2cd826ff.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_2cd826ff.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_6aa14400.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_6aa14400.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Tricascade_Non_Organic_E_waste_a775c5a7.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Tricascade_Non_Organic_E_waste_a775c5a7.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Green_Glass_cdd7ffb6.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Green_Glass_cdd7ffb6.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Tricascade_Non_Organic_E_waste_3e0cd887.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Tricascade_Non_Organic_E_waste_3e0cd887.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Metal_f521e337.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Metal_f521e337.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Cardboard_2b53d1a3.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Cardboard_2b53d1a3.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_120a6863.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_120a6863.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_bf69e6b5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_bf69e6b5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_White_Glass_456ca262.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_White_Glass_456ca262.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_White_Glass_0830aaa6.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_White_Glass_0830aaa6.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Metal_098947e8.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Metal_098947e8.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Green_Glass_bd5f6309.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Green_Glass_bd5f6309.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/MendleyGCdataset_Non_Organic_61b33c66.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/MendleyGCdataset_Non_Organic_61b33c66.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/MendleyGCdataset_Non_Organic_da2cec38.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/MendleyGCdataset_Non_Organic_da2cec38.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Plastic_a7fd6f3e.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Plastic_a7fd6f3e.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Cardboard_3dcd5c2d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Cardboard_3dcd5c2d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_cdf61445.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_cdf61445.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Metal_26974090.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Metal_26974090.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Metal_934298c9.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Metal_934298c9.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Brown_Glass_a6a6c6fb.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Brown_Glass_a6a6c6fb.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_White_Glass_c466e5ad.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_White_Glass_c466e5ad.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Tricascade_Non_Organic_E_waste_feb39d34.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Tricascade_Non_Organic_E_waste_feb39d34.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_b7ca65dd.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_b7ca65dd.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_f14a68e4.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_f14a68e4.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_1f67941a.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_1f67941a.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_43eb477d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_43eb477d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_6640163b.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_6640163b.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Paper_db1dfa9d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Paper_db1dfa9d.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Green_Glass_e609b174.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Green_Glass_e609b174.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Paper_9b6a18c7.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Paper_9b6a18c7.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Warp-main_Non_Organic_Plastic_4243dacd.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Warp-main_Non_Organic_Plastic_4243dacd.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Plastic_34a2225a.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Plastic_34a2225a.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Cardboard_5d534a44.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Cardboard_5d534a44.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Tricascade_Non_Organic_E_waste_6c897f8c.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Tricascade_Non_Organic_E_waste_6c897f8c.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/Trashnet_Non_Organic_Cardboard_e132d1d8.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/Trashnet_Non_Organic_Cardboard_e132d1d8.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Cardboard_3e9151b5.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Cardboard_3e9151b5.jpg
Moved: /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1/Non_Organic/garbage_classification_Non_Organic_Cardboard_27618a0d.jpg -> /Users/kalyanivenkateswaran/Documents/T3_Project/waste_classification/data/consolidated/Stage-1-duplicates/Non_Organic/garbage_classification_Non_Organic_Cardboard_27618a0d.jpg

In [39]:
duplicates_no_cleanup = find_duplicates(DIR_2)

print("Number of duplicates:", len(duplicates_no_cleanup))

/opt/anaconda3/envs/t3_project_clone/lib/python3.11/site-packages/PIL/Image.py:970: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

Number of duplicates: 0

In [40]:
duplicates_org_cleanup = find_duplicates(DIR_3)

print("Number of duplicates:", len(duplicates_org_cleanup))

Number of duplicates: 0

In [41]:
stage2_root = BASE_DIR / "data" / "consolidated" / "Stage-2"

all_duplicates_cleanup = []
summary_cleanup = []

for class_folder in os.listdir(stage2_root):

    class_path = os.path.join(stage2_root, class_folder)

    if os.path.isdir(class_path):

        print(f"Checking {class_folder}...")

        duplicates_cleanup = find_duplicates(class_path)

        summary_cleanup.append({
            "class": class_folder,
            "duplicate_count": len(duplicates)
        })

        for dup in duplicates_cleanup:
            all_duplicates_cleanup.append((class_folder, dup[0], dup[1]))

Checking Paper...
Checking Misc_Trash...
Checking Textile...
Checking Metal...
Checking E_waste...

/opt/anaconda3/envs/t3_project_clone/lib/python3.11/site-packages/PIL/Image.py:970: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

Checking Medical_waste...
Checking Cardboard...
Checking Green_Glass...
Checking Brown_Glass...
Checking Battery...
Checking Plastic...
Checking Shoes...
Checking White_Glass...

In [42]:
all_duplicates_cleanup

[]